[build]
builder = "nixpacks"

[deploy]
startCommand = "python manage.py migrate && python manage.py collectstatic --noinput && gunicorn activity_album.wsgi --workers 2 --bind 0.0.0.0:$PORT"
healthcheckPath = "/"
restartPolicyType = "on_failure"
