# Generated by Django 6.0.5 on 2026-06-10 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0004_create_member_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdocument',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
